### ISSUE TITLE
Add a PR-time build + fast-unit-test CI gate (semantic merge breaks reach main undetected)

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-foundation#544]
## Problem

There is no PR-time build or test gate. Both existing workflows trigger on `push` only:

- `.github/workflows/docker.yml` — `push: branches: [main]` (runs **after** merge).
- `.github/workflows/packages.yml` — `push` to `feat/*` `fix/*` `bug/*` … (not `claude/*`, and **not** `pull_request`); it packs/compiles the **library** projects but deliberately does not build test projects or run any tests ("The full test suite is intentionally NOT run here … testing belongs in a separate CI workflow").

Net effect: a PR can merge to `main` with a compile error or failing tests and nothing catches it.

## Concrete failure this caused

[#543](https://github.com/elsa-workflows/elsa-foundation/pull/543) fixed a `main` that did not compile. [#539](https://github.com/elsa-workflows/elsa-foundation/pull/539) removed the `ActivityVersionHashMismatchException.Version` property (splitting it into `PersistedVersion`/`IncomingVersion`); [#541](https://github.com/elsa-workflows/elsa-foundation/pull/541) branched earlier and added a test asserting the old `.Version`. Each PR compiled on its own branch, so there was **no textual merge conflict** — but the merged result did not compile:

```
HashMismatchTests.cs(96,43): error CS1061: 'ActivityVersionHashMismatchException' does not contain a definition for 'Version'
```

This merged undetected and sat broken on `main` until caught by a manual local test run. This is a **semantic merge conflict** — exactly the class of break a per-PR `dotnet build` catches and human review + textual-conflict detection does not. It has now bitten multiple merges in quick succession.

## Proposal — minimal PR gate

Add a `.github/workflows/ci.yml` triggered on `pull_request` (targeting `main`) that does the cheap, high-value checks, without pulling in the heavy Testcontainers integration suite the maintainer intentionally excluded from `packages.yml`:

1. **`dotnet build` the full solution, including test projects** (`-warnaserror` optional). This alone would have caught #543 — no containers, ~single-digit minutes.
2. **Run the non-integration unit tests** — the `Tests/Unit` fast tests (filter out Testcontainers-backed integration tests, or use a trait/category). Keeps the gate fast and container-free.

Explicitly out of scope for this gate (leave as follow-up / nightly): the Testcontainers-based integration suite, which needs Docker and is slower.

## Acceptance criteria

- A PR that fails to compile (including semantic merge conflicts across two green branches) is blocked / shows a red check before merge.
- The workflow does not start Docker containers.
- Make it a required status check on `main` (repo setting) so the red check actually blocks merge.

## Notes

Per repo history the minimal-CI posture was a deliberate ruling, so this proposes an **additive** compile+fast-unit gate rather than moving the full suite into CI. If even that is unwanted, an alternative is a lighter-weight local pre-merge convention — but semantic breaks like #543 are invisible to local single-branch testing by construction, so a server-side check is the only reliable catch.
